## numpy array 생성

In [2]:
import numpy as np

In [3]:
a = [1,2,3,4]
print(type(a), a)

<class 'list'> [1, 2, 3, 4]


In [4]:
b = np.array(a)
print(type(b), b)

<class 'numpy.ndarray'> [1 2 3 4]


In [5]:
a = np.array([1,2,3,4])
print(a[1], a[-1], a[1:], a[::2])

2 4 [2 3 4] [1 3]


## 대표적인 numpy 메소드

In [6]:
print(np.arange(10))
print(np.arange(1,10,2))
print(np.arange(1,2,0.1))

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]


In [7]:
print(np.zeros(2))
print(np.ones(2))
print(np.eye(2))

[0. 0.]
[1. 1.]
[[1. 0.]
 [0. 1.]]


In [9]:
print(np.sqrt(2))
print(np.pi)
print(np.sin(np.pi/2))
print(np.cos(0))

1.4142135623730951
3.141592653589793
1.0
1.0


In [10]:
print(np.random.randn(5))
print(np.random.choice(10,5))

[-0.27451844 -1.20605235  0.06163136 -0.51064044 -1.65851177]
[6 2 5 0 0]


## n차원 행렬 만들기

In [11]:
a = np.arange(10).reshape(2,5)
print(a)

print(a.shape)
print(a.ndim)
print(a.size)

[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)
2
10


In [12]:
a = np.arange(10).reshape(2,5)
print(a)

print(a[1,2])
print(a[(0,3)])

[[0 1 2 3 4]
 [5 6 7 8 9]]
7
3


## 행렬 연산

In [14]:
a = np.array([[1,2,3],[3,2,5]])
b = np.array([[-1,3,5],[1,4,2]])
print(a)
print(b)
print()
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[1 2 3]
 [3 2 5]]
[[-1  3  5]
 [ 1  4  2]]

[[0 5 8]
 [4 6 7]]
[[ 2 -1 -2]
 [ 2 -2  3]]
[[-1  6 15]
 [ 3  8 10]]
[[-1.          0.66666667  0.6       ]
 [ 3.          0.5         2.5       ]]


In [15]:
c = np.dot(a,b.transpose())
print(c)

d = np.dot(a.T,b)
print(d)

[[20 15]
 [28 21]]
[[ 2 15 11]
 [ 0 14 14]
 [ 2 29 25]]


In [16]:
a = np.zeros(5) + 2
print(a)

b = np.ones(5) - 2
print(b)

[2. 2. 2. 2. 2.]
[-1. -1. -1. -1. -1.]


In [17]:
a = np.arange(-3, 3)
print(a)
print(a<0)
print(a[a<0])
print(a[abs(a)>2])

[-3 -2 -1  0  1  2]
[ True  True  True False False False]
[-3 -2 -1]
[-3]


## 데이터 프레임 만들기

In [18]:
import pandas as pd

In [20]:
df = pd.DataFrame(np.random.randn(3,2), index=['m1','m2','m3'], columns=['price','num'])
df

price       num
m1 -0.437169  0.129002
m2  1.414006  0.767042
m3 -0.642720 -0.544914

## 특정 열 접근 및 마스킹

In [22]:
print(df, '\n')
print(df['num'], '\n')
print(df['num']>0.5, '\n')

df2 = df[df['num']>0.5]
print(df2)

       price       num
m1 -0.437169  0.129002
m2  1.414006  0.767042
m3 -0.642720 -0.544914 

m1    0.129002
m2    0.767042
m3   -0.544914
Name: num, dtype: float64 

m1    False
m2     True
m3    False
Name: num, dtype: bool 

       price       num
m2  1.414006  0.767042


## 행과 열 전치

In [25]:
df = pd.DataFrame(np.random.randn(3,2), index=['m1','m2','m3'], columns=['price', 'num'])
df.T

m1        m2        m3
price  0.791079  0.493072  0.549979
num    1.408990 -0.142039 -1.605707

## 컬럼 간 연산

In [26]:
df = pd.DataFrame(np.random.randn(3,2), index=['m1','m2','m3'], columns=['price', 'num'])
df['rate'] = df['price']/df['num']
df

price       num      rate
m1  0.816594  0.151650  5.384725
m2  0.839122  0.939220  0.893424
m3  0.467214  1.926836  0.242477

## 인덱스(행) 내 연산

In [28]:
df = pd.DataFrame(np.random.randn(3,2), index=['m1','m2','m3'], columns=['price', 'num'])
df['sum'] = np.sum(df, axis=1)
df

price       num       sum
m1  1.590966  0.040047  1.631013
m2  0.071088  0.655586  0.726674
m3 -1.648104  0.083000 -1.565104